function PloterMatrice(M)
[m,n]=size(M);
for rowCnt=1:m,
	for colCnt=1:n,
		numberString=num2str(M(rowCnt,colCnt));
		text(colCnt-.5,m-rowCnt+.5,numberString, ...
		'HorizontalAlignment','center', ...
		'Color', 'k', ...
		'FontWeight','bold', ...
		'FontSize', 14);
	end;
end;
set(gca,'Box','on', ...
'Visible','on', ...
'xLim',[0 n], ...
'xGrid','on', ...
'xTickLabel',[], ...
'xTick',0:n, ...
'yGrid','on', ...
'yLim',[0 m], ...
'yTickLabel',[], ...
'yTick',0:m, ...
'DataAspectRatio',[1, 1, 1], ...
'GridLineStyle',':', ...
'LineWidth',3, ...
'XColor','k', ...
'YColor','k');
